name: ${project.name}
version: ${project.version}-git-${githash}-${build.number}
description: ${project.description}
author: ${bukkit.pluginyml.author}
main: ${bukkit.pluginyml.main}
load: STARTUP
depend: [CrackShot, WorldGuard, kCore, DatenClient]

commands:
  resourcepack:
    description: Get the resource pack
    aliases: [rp]
    permission: warz.command.resourcepack.use
  warz:
    description: Main WarZ command
    permission: warz.command.warz.see
    aliases: [wz]
  spawn:
    description: Teleport to the spawn
    permission: warz.command.spawn
  back:
    description: Teleport to the map
    permission: warz.command.back
    aliases: [start]
  shop:
    description: Open the shop
    permission: warz.command.shop

permissions:
  warz.command.resourcepack.use:
    default: true
