name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${bukkit.pluginyml.author}
main: ${bukkit.pluginyml.main}

depend: [CrackShot, WorldGuard]

commands:
  resourcepack:
    description: Get the resource pack
    aliases: [rp]
    permission: warz.command.resourcepack.use
  warz:
    description: Get the resource pack
    permission: warz.command.warz.see

permissions:
  warz.command.resourcepack.use:
    default: true
